### ISSUE TITLE
多个离线训练的job合并为一个预测任务

### ISSUE THREAD

**Issue by huajinghua** [FederatedAI/FATE-Serving#109]
1. 由于现实场景问题，我们在使用时会将建模流程分为多个job,比如预处理是一个jobA，逻辑回归模型训练和评分卡是另一个jobB

2. 在预测过程中，我们希望这两个job的模型能在一个预测pipeline里面按顺序完成预测，比如给出一个样本后, serving过程经过jobA的pipeline和jobB的pipeline，然后再返回结果

希望能支持以上模式，谢谢

**Comment by dylan-fan** [comment]
如果 FATE 提供一个model loader组件，实现跨job模型复用，是不是可以解决你们问题？
模型训练jobB需要用到JOBA的模型，直接在JOBB里面加一个modelloader组件加载jobA模型。这样发布模型时候只要发布一就可以了
