### ISSUE TITLE
通过API unbind 和unload

### ISSUE THREAD

**Issue by turkeymz** [FederatedAI/FATE-Serving#113]
请问有没有unbind 和unload的API文档。
暂时我只找到总fate-serving-admin页面上按钮点击，但我想类似load的那样，通过API来操作

**Comment by GentleWang1011** [comment]
在README.md中有document的超链接，里面有【如何加载模型及验证】板块，可以点进去详细看下能不能解决您的疑问

**Comment by hqsh** [comment]
您好，你能否跑通一个 fate-serving 的模型？我用官方 demo 跑，预测结果总是 score 0（https://github.com/FederatedAI/FATE-Serving/issues/138）。

如果您能跑通，能否分享一下您的模型训练、发布相关 pipeline 代码，或者命令行 dsl、conf 方式也可以？

该问题困扰了很久，所以冒昧打扰了。感谢！

**Comment by turkeymz** [comment]
> 您好，你能否跑通一个 fate-serving 的模型？我用官方 demo 跑，预测结果总是 score 0（[https://github.com/FederatedAI/FATE-Serving/issues/138）。](https://github.com/FederatedAI/FATE-Serving/issues/138%EF%BC%89%E3%80%82)
> 
> 如果您能跑通，能否分享一下您的模型训练、发布相关 pipeline 代码，或者命令行 dsl、conf 方式也可以？
> 
> 该问题困扰了很久，所以冒昧打扰了。感谢！

我用的是鸢尾花数据集，把花瓣和花萼拆开了。然后预测是随便造数据的。
这是我的dsl:
{
        "components": {
            "dataio_10000035": {
                "input": {
                    "data": {
                        "data": [
                            "reader_0.data"
                        ]
                    }
                },
                "isML": false,
                "module": "DataIO",
                "output": {
                    "data": [
                        "data"
                    ],
                    "model": [
                        "model"
                    ]
                }
            },
            "reader_0": {
                "isML": false,
                "module": "Reader",
                "output": {
                    "data": [
                        "data"
                    ],
                    "model": [
                        "model"
                    ]
                }
            },
            "intersection_24353697": {
                "input": {
                    "data": {
                        "data": [
                            "dataio_10000035.data"
                        ]
                    }
                },
                "isML": false,
                "module": "Intersection",
                "output": {
                    "data": [
                        "data"
                    ]
                }
            },
            "evaluation_18815533": {
                "input": {
                    "data": {
                        "data": [
                            "heterolr_51264038.data"
                        ]
                    }
                },
                "isML": false,
                "module": "Evaluation",
                "output": {
                    "data": [
                        "data"
                    ],
                    "model": [
                        "model"
                    ]
                }
            },
            "heterolr_51264038": {
                "input": {
                    "data": {
                        "train_data": [
                            "intersection_24353697.data"
                        ]
                    }
                },
                "isML": true,
                "module": "HeteroLR",
                "output": {
                    "data": [
                        "data"
                    ],
                    "model": [
                        "model"
                    ]
                }
            }
        }
    }
