### ISSUE TITLE
What's the difference between FATE-serving & FATE

### ISSUE THREAD

**Issue by libratiger** [FederatedAI/FATE-Serving#114]
Why I can not using the FATE for the serving.
In tensorflow-serving can be different with tensorflow, but I do not see much difference between FATE & FATE-Serving. And this repo is not updated for a long time.

**Comment by GentleWang1011** [comment]
Fate-serving is the online part of Fate. Fate-serving can be used for online joint predictions after federation modeling with Fate is completed.It's still being updated,the new feature is in private beta.

**Comment by libratiger** [comment]
But you do not answer my question, what's the function does fate do not provided compared with fate-serving.
