### ISSUE TITLE
是否可以手动执行load和bind，假设fate-serving和fate-flow之间均无法联通？

### ISSUE THREAD

**Issue by kimamen** [FederatedAI/FATE-Serving#121]
假设guest和host部署的fate-serving因为某种原因无法连接各自的fate-flow，那是否有方法可以手动发布模型到fate-serving上呢

**Comment by hqsh** [comment]
您好，你能否跑通一个 fate-serving 的模型？我用官方 demo 跑，预测结果总是 score 0（https://github.com/FederatedAI/FATE-Serving/issues/138）。

如果您能跑通，能否分享一下您的模型训练、发布相关 pipeline 代码，或者命令行 dsl、conf 方式也可以？

该问题困扰了很久，所以冒昧打扰了。感谢！
