### ISSUE TITLE
可否提供一下多节点（至少三方）的部署案例？

### ISSUE THREAD

**Issue by wangmatlab** [FederatedAI/FATE-Serving#124]
可否提供一下多节点（至少三方）的部署案例？特别是针对serving-proxy路由表的配置。

**Comment by hqsh** [comment]
您好，你能否跑通一个 fate-serving 的模型？我用官方 demo 跑，预测结果总是 score 0（https://github.com/FederatedAI/FATE-Serving/issues/138）。

如果您能跑通，能否分享一下您的模型训练、发布相关 pipeline 代码，或者命令行 dsl、conf 方式也可以？

该问题困扰了很久，所以冒昧打扰了。感谢！

**Comment by wangmatlab** [comment]
我是通过docker-compose部署的三方节点 按照官网给的流程进行部署和测试。现在才看到您的消息，也不知您解决了没有。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月10日(星期四) 下午5:12
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [FederatedAI/FATE-Serving] 可否提供一下多节点（至少三方）的部署案例？ (Issue #124)





 
您好，你能否跑通一个 fate-serving 的模型？我用官方 demo 跑，预测结果总是 score 0（https://github.com/FederatedAI/FATE-Serving/issues/138）。
 
如果您能跑通，能否分享一下您的模型训练、发布相关 pipeline 代码，或者命令行 dsl、conf 方式也可以？
 
该问题困扰了很久，所以冒昧打扰了。感谢！
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by tigflanker** [comment]
我想问下如果3方纵向FATE，这个conf应该怎么写啊，哪位大佬好心丢个实例？

{
    "dsl_version":2,
    "initiator":{
        "role":"guest",
        "party_id":9999
    },
    "role":{
        "arbiter":[10000],
        "host":[10000],
        "guest":[9999]
    },
... ...

role里的host、guest都是键，我们自己改成host1、host2，不行吧？
