### ISSUE TITLE
请问fate-serving2.1.0的checkup中出现“fateflow is not found in  zookeeper”，应该如何解决？

### ISSUE THREAD

**Issue by wangmatlab** [FederatedAI/FATE-Serving#125]

**Comment by wozitaoran** [comment]
我也遇到了这个问题：
192.168.19.37:8000 : check fateflow in zookeeperfateflow is not found in zookeeper
192.168.19.37:8000 : check model loadedmodel is not loaded

**Comment by nicesteven** [comment]
这个应该不是致命的，我这边也有提示，也是可以做在线预测使用
