### ISSUE TITLE
单笔推理和批量推理结果不一

### ISSUE THREAD

**Issue by stone-wlg** [FederatedAI/FATE-Serving#147]
单笔推理和批量推理结果不一
Fate Version 1.8.0
Fate Serving Version 2.1.5

1. 单笔推理结果
{ "retcode": 0, "retmsg": "", "caseid": "", "data": { "score": 0.9132008044323787, "modelId": "guest#1000#guest-1000#host-2000#model", "modelVersion": "202205220752224224370", "timestamp": 1653205972739 }, "log": {}, "warn": {}, "flag": 0 }
{ "retcode": 0, "retmsg": "", "caseid": "", "data": { "score": 0.8994726383954806, "modelId": "guest#1000#guest-1000#host-2000#model", "modelVersion": "202205220752224224370", "timestamp": 1653205972739 }, "log": {}, "warn": {}, "flag": 0 }
2. 批量推理结果
{ "retcode": 0, "retmsg": "", "caseid": "512429879b5a46a88cf9f96203d2caa8", "data": { "modelId": "guest#1000#guest-1000#host-2000#model", "modelVersion": "202205220752224224370", "timestamp": 1653205972739 }, "log": {}, "warn": {}, "flag": 0, "batchDataList": [ { "index": 0, "retcode": 0, "retmsg": "", "data": { "score": 0.9132008044323787 } }, { "index": 1, "retcode": 0, "retmsg": "", "data": { "score": 0.9132008044323787 } } ], "singleInferenceResultMap": { "0": { "index": 0, "retcode": 0, "retmsg": "", "data": { "score": 0.9132008044323787 } }, "1": { "index": 1, "retcode": 0, "retmsg": "", "data": { "score": 0.9132008044323787 } } } }

**Comment by NookLook2014** [comment]
请问你是用的什么adapter，才有结果输出的啊？
