### ISSUE TITLE
Fate-Serving源碼問題

### ISSUE THREAD

**Issue by ZhouHaoH** [FederatedAI/FATE-Serving#173]
無法導入com.webank.ai.fate.api包，請這個包在哪
![image](https://github.com/FederatedAI/FATE-Serving/assets/87072734/31c52df0-6dcc-4352-8f7d-ce96b015ab7f)

**Comment by Young-Ta0** [comment]
downloaded the fate-serving-admin-2.1.6-release.zip file from the following URL: [快速部署](https://fate-serving.readthedocs.io/en/develop/quickstart/quickstart/.)  import the fate-serving-admin-2.1.6.jar file from the zip into this project

**Comment by Young-Ta0** [comment]
> 無法導入com.webank.ai.fate.api包，請這個包在哪 ![image](https://user-images.githubusercontent.com/87072734/246343303-31c52df0-6dcc-4352-8f7d-ce96b015ab7f.png)
downloaded the fate-serving-admin-2.1.6-release.zip file from the following URL: [快速部署](https://fate-serving.readthedocs.io/en/develop/quickstart/quickstart/.)  import the fate-serving-admin-2.1.6.jar file from the zip into this project

**Comment by forgivedengkai** [comment]
这是可以自动生成的，  在源码更目录下执行 mvn clean compile 会自动生成 proto中定义的类
