### ISSUE TITLE
auth信息错误时持续重复请求

### ISSUE THREAD

**Issue by zx247549135** [FederatedAI/FATE-Serving#55]
fate serving 1.2.2版本
1、配置auth_config，配置两方appId和app_key均对应。正常请求。
2、配置auth_config，配置两方appId和app_key对应不上，发现proxy持续请求错误日志
![image](https://user-images.githubusercontent.com/8498396/79749959-b4a4c980-8342-11ea-8457-ed0bc8832781.png)

**Comment by liuluyeah** [comment]
想问下为什么不要配置第三方呢，纵向不是需要有第三方作为仲裁者吗？

**Comment by dylanxu90** [comment]
此处显示日志为路由查询时打印日志，配置auth_config并不会导致持续打印日志，问题可能是路由表中配置default->default为当前proxy地址造成循环请求，检查下route_table.json的配置
