### ISSUE TITLE
建议提供构建docker镜像的过程，如FATE/docker-build/

### ISSUE THREAD

**Issue by Paul0M** [FederatedAI/FATE-Serving#92]
如题

**Comment by sunyinggang** [comment]
同上，建议提供构建docker镜像的过程

**Comment by hqsh** [comment]
您好，你能否跑通一个 fate-serving 的模型？我用官方 demo 跑，预测结果总是 score 0（https://github.com/FederatedAI/FATE-Serving/issues/138）。

如果您能跑通，能否分享一下您的模型训练、发布相关 pipeline 代码，或者命令行 dsl、conf 方式也可以？

该问题困扰了很久，所以冒昧打扰了。感谢！
