### ISSUE TITLE
 No inference results were obtained

### ISSUE THREAD

**Issue by ssdyue** [FederatedAI/FATE-Serving#96]
This is a test result after I deployed the fate-serving based on cluster and pubished the trained model named _lr-test:_
**request body**:
`{
    "serviceId": "lr-test",
    "featureData": {
        "x0": 1.88669,
        "x1": -1.359293,
        "x2": 2.303601,
        "x3": 2.00137,
        "x4": 1.307686
    },
    "sendToRemoteFeatureData": {
        "phone_num": "122222222"
    }
}`

**response**:
`{ "retcode": 0, "retmsg": "", "caseid": "", "data": { "modelId": "guest#9999#arbiter-10000#guest-9999#host-10000#model", "modelVersion": "202012161128225158102", "timestamp": 1608089601776 }, "log": {}, "warn": {}, "flag": 0 }`

Obviously, no meaningful results were obtained. I think there is a problem, but how do I solve it?

**Comment by ioracion** [comment]
I encountered the same problem bro... is your problem solved?
